server:
  port: 8082

# The application name is used to fetch the correct configuration file (e.g., notification-service.yml)
spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:"

---
# Configuration for the 'local' Spring profile for running outside of Docker
spring:
  config:
    activate:
      on-profile: "local"
    # Tells Spring to load our local.env file for secrets
    import: "optional:file:./local.env[.properties]"
  cloud:
    config:
      # When running locally, we might need to use localhost to find the config server
      uri: http://localhost:8888