server:
  port: 9191

# The application name is used to fetch the correct configuration file (e.g., load-product.yml)
spring:
  application:
    name: load-product
  config:
    import: "optional:configserver:"

# All other configuration is now fetched from the Spring Cloud Config Server.

---
# Configuration for the 'local' Spring profile for running outside of Docker
spring:
  config:
    activate:
      on-profile: "local"
    import: "optional:file:./local.env[.properties]"
  cloud:
    config:
      # When running locally, we use localhost to find the config server
      uri: http://localhost:8888
