server:
  port: 8084 # Port on which the API Gateway will run

spring:
  application: # The application name is used to fetch the correct configuration file
    name: api-gateway
  config:
    import: "optional:configserver:"

---
# Configuration for the 'local' Spring profile for running outside of Docker
spring:
  config:
    activate:
      on-profile: "local"
  cloud:
    config:
      # When running locally, we use localhost to find the config server
      uri: http://localhost:8888
